FROM node:22 AS web-builder

COPY web/package.json web/package-lock.json /web/
COPY web/shared/package.json /web/shared/package.json
COPY web/frpc/package.json /web/frpc/package.json
COPY web/frps/package.json /web/frps/package.json
WORKDIR /web
RUN npm ci --prefer-offline
COPY web/shared/ /web/shared/
COPY web/frps/ /web/frps/
WORKDIR /web/frps
RUN npm run build

FROM golang:1.25 AS building

COPY . /building
COPY --from=web-builder /web/frps/dist /building/web/frps/dist
WORKDIR /building

RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frps -o bin/frps ./cmd/frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
